# Generated by Django 4.2.14 on 2024-08-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_version', models.IntegerField(help_text='Введите номер версии продукта', verbose_name='Версия')),
                ('name', models.CharField(help_text='Введите название версии продукта', max_length=150, verbose_name='Название версии')),
                ('is_current_version', models.BooleanField(default=False, help_text='Признак текущей версии', verbose_name='Признак версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('name',),
            },
        ),
    ]
