# Generated by Django 4.2.14 on 2024-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_edit_is_posted', 'Опубликовать'), ('can_edit_description', 'Редактировать описание'), ('can_change_category', 'Изменить категорию')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='Признак публикации', verbose_name='Опубликован'),
        ),
    ]
